### ISSUE TITLE
 zcompute fails to build on Zig 0.12.0

### ISSUE THREAD

**Issue by happysmash27** [silversquirl/zcompute#1]
It looks like this is the dependency that [Slimy is failing to build](https://github.com/silversquirl/slimy/issues/2) due to.

As with Slimy, at first it fails to `zig build` due to:
```
/mnt/Biblioteko/Gits/Build/Slimeydeps/zcompute/build.zig.zon:1:2: error: missing top-level 'paths' field
.{
 ^
```

Which, just like Slimey, can be fixed by adding `.paths = .{""},` to `build.zig.zon`:
```
.{
    .name = "zcompute",
    .version = "0.1.0-dev",
    .dependencies = .{
        .vulkan_zig = .{
            .url = "https://github.com/Snektron/vulkan-zig/archive/1e4e90ffb14084357265d79b58e5f1b1c9396069.tar.gz",
            .hash = "1220d3e1254af9c8fd4c3f09bd9f50f51dc5eaa5506f845ed67bcd75e1e2961ce1ea",
        },
    },
    .paths = .{""},
}
```

It then brings up the same error in `vulkan_zig` stopping me from building Slimy:
```
/home/happysmash27/.cache/zig/p/1220d3e1254af9c8fd4c3f09bd9f50f51dc5eaa5506f845ed67bcd75e1e2961ce1ea/generator/vulkan/build_integration.zig:77:22: error: expected 2 arguments, found 3
        const self = @fieldParentPtr(GenerateStep, "step", step);
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/happysmash27/.cache/zig/p/1220d3e1254af9c8fd4c3f09bd9f50f51dc5eaa5506f845ed67bcd75e1e2961ce1ea/generator/xml.zig:235:13: error: local variable is never mutated
        var end = mem.indexOfScalarPos(u8, self.source, self.offset, '\n') orelse self.source.len;
            ^~~
/home/happysmash27/.cache/zig/p/1220d3e1254af9c8fd4c3f09bd9f50f51dc5eaa5506f845ed67bcd75e1e2961ce1ea/generator/xml.zig:235:13: note: consider using 'const'
/home/happysmash27/.cache/zig/p/1220d3e1254af9c8fd4c3f09bd9f50f51dc5eaa5506f845ed67bcd75e1e2961ce1ea/generator/vulkan/parse.zig:26:9: error: local variable is never mutated
    var reg = registry.Registry{
        ^~~
/home/happysmash27/.cache/zig/p/1220d3e1254af9c8fd4c3f09bd9f50f51dc5eaa5506f845ed67bcd75e1e2961ce1ea/generator/vulkan/parse.zig:26:9: note: consider using 'const'
/home/happysmash27/.cache/zig/p/1220d3e1254af9c8fd4c3f09bd9f50f51dc5eaa5506f845ed67bcd75e1e2961ce1ea/generator/vulkan/parse.zig:42:9: error: local variable is never mutated
    var commands_elem = root.findChildByTag("commands") orelse return error.InvalidRegistry;
        ^~~~~~~~~~~~~
/home/happysmash27/.cache/zig/p/1220d3e1254af9c8fd4c3f09bd9f50f51dc5eaa5506f845ed67bcd75e1e2961ce1ea/generator/vulkan/parse.zig:42:9: note: consider using 'const'
/home/happysmash27/.cache/zig/p/1220d3e1254af9c8fd4c3f09bd9f50f51dc5eaa5506f845ed67bcd75e1e2961ce1ea/generator/vulkan/parse.zig:41:9: error: local variable is never mutated
    var types_elem = root.findChildByTag("types") orelse return error.InvalidRegistry;
        ^~~~~~~~~~
/home/happysmash27/.cache/zig/p/1220d3e1254af9c8fd4c3f09bd9f50f51dc5eaa5506f845ed67bcd75e1e2961ce1ea/generator/vulkan/parse.zig:41:9: note: consider using 'const'
/home/happysmash27/.cache/zig/p/1220d3e1254af9c8fd4c3f09bd9f50f51dc5eaa5506f845ed67bcd75e1e2961ce1ea/generator/build_integration.zig:171:22: error: expected 2 arguments, found 3
        const self = @fieldParentPtr(ShaderCompileStep, "step", step);
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mnt/Biblioteko/Gits/Build/Slimeydeps/zcompute/build.zig:9:10: error: no field named 'source_file' in struct 'Build.Module.CreateOptions'
        .source_file = .{ .path = "src/zcompute.zig" },
         ^~~~~~~~~~~
/usr/lib64/zig/0.12.0/lib/std/Build/Module.zig:139:27: note: struct declared here
pub const CreateOptions = struct {
                          ^~~~~~
referenced by:
    runBuild__anon_8991: /usr/lib64/zig/0.12.0/lib/std/Build.zig:2079:27
    main: /usr/lib64/zig/0.12.0/lib/compiler/build_runner.zig:300:29
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
/home/happysmash27/.cache/zig/p/1220d3e1254af9c8fd4c3f09bd9f50f51dc5eaa5506f845ed67bcd75e1e2961ce1ea/build.zig:33:14: error: no field named 'source_file' in struct 'Build.Module.CreateOptions'
            .source_file = generate_cmd.addOutputFileArg("vk.zig"),
             ^~~~~~~~~~~
/usr/lib64/zig/0.12.0/lib/std/Build/Module.zig:139:27: note: struct declared here
pub const CreateOptions = struct {
                          ^~~~~~
```

It looks like the version for `vulkan-zig` needs to be updated, and as with Slimey, I imagine there could be other issues, too.

**Comment by happysmash27** [comment]
If it's updated to be:
```
.{
    .name = "zcompute",
    .version = "0.1.0-dev",
    .dependencies = .{
        .vulkan_zig = .{
            .url = "https://github.com/Snektron/vulkan-zig/archive/9f6e6177b1fdb3ed22231d9216a24480e84cfa5e.tar.gz",
            .hash = "1220f2961df224f7d35dee774b26194b8b937cc252fa8e4023407776c58521d53e38",
        },
    },
    .paths = .{""},
}
```

The error changes to:
```
/mnt/Biblioteko/Gits/Build/Slimeydeps/zcompute/build.zig:9:10: error: no field named 'source_file' in struct 'Build.Module.CreateOptions'
        .source_file = .{ .path = "src/zcompute.zig" },
         ^~~~~~~~~~~
/usr/lib64/zig/0.12.0/lib/std/Build/Module.zig:139:27: note: struct declared here
pub const CreateOptions = struct {
                          ^~~~~~
referenced by:
    runBuild__anon_8991: /usr/lib64/zig/0.12.0/lib/std/Build.zig:2079:27
    main: /usr/lib64/zig/0.12.0/lib/compiler/build_runner.zig:300:29
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

**Comment by happysmash27** [comment]
I think it can be fixed by changing it to `root_source_file`?
https://ziggit.dev/t/error-no-field-named-source-file-in-struct-build-module-createoptions/4104

I did this and the error changes to:
```
/mnt/Biblioteko/Gits/Build/Slimeydeps/zcompute/build.zig:10:10: error: no field named 'dependencies' in struct 'Build.Module.CreateOptions'
        .dependencies = &.{
         ^~~~~~~~~~~~
/usr/lib64/zig/0.12.0/lib/std/Build/Module.zig:139:27: note: struct declared here
pub const CreateOptions = struct {
                          ^~~~~~
referenced by:
    runBuild__anon_8991: /usr/lib64/zig/0.12.0/lib/std/Build.zig:2079:27
    main: /usr/lib64/zig/0.12.0/lib/compiler/build_runner.zig:300:29
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

Zig 0.12.0 sure has a lot of breaking changes…

**Comment by silversquirl** [comment]
As of #2, zcompute should now build on 0.13.0, the latest stable version.
0.12.0 will not be supported.
